### ISSUE TITLE
Combination of VIIRS and SENTINEL2 sensors

### ISSUE THREAD

**Issue by anikfal** [TimHessels/SEBAL#10]
In this combination, the thermal band is derived from VIIRS. Since the overpassing times of VIIRS and SENTINEL2 are different from each other, cloud coverage for each of these 2 images are not the same. I wonder if this issue can cause problems in the results.

For example, a cloudy region has a high albedo and low temperature, while in the aforementioned condition, the high albedo from SENTINEL2 may not conform to the low thermal value (cloud coverage) from VIIRS.

**Comment by TimHessels** [comment]
Yes this can have a negative effect on the results. Some pre-processing is required if you want to combine S2 and VIIRS. You can add a quality mask in the Additional_input tab, or replace the cloud pixels in the S2 and VIIRS by nan values and use those adjusted maps within SEBAL.
