### ISSUE TITLE
Biomass production

### ISSUE THREAD

**Issue by anikfal** [TimHessels/SEBAL#12]
Is there any reference discussing the formulations of the biomass production implemented in pySEBAL?

**Comment by TimHessels** [comment]
Here is some reference:
https://pure.tudelft.nl/ws/portalfiles/portal/139161127/1_s2.0_S0304380022002800_main.pdf

**Comment by anikfal** [comment]
Could I know the reference of the coefficient (`0.864`) used in the formula below? I didn't find it in the paper you suggested in https://github.com/TimHessels/SEBAL/issues/12#issuecomment-1484603680
https://github.com/TimHessels/SEBAL/blob/2f6454f0df77a25bcc94cbed63af68c7d0583dd8/pySEBAL/pySEBAL_code.py#L1210

**Comment by TimHessels** [comment]
The 0.864 is an unit conversion factor.
