### ISSUE TITLE
Cloud mask

### ISSUE THREAD

**Issue by anikfal** [TimHessels/SEBAL#13]
Is there any reference discussing the cloud mask algorithm implemented in pySEBAL?

**Comment by TimHessels** [comment]
In pySEBAL there is no specific algorithm applied to calculate cloud mask. It is based on a simple NDVI criteria and the QC maps. But the user can use their own cloud mask as input for pySEBAL by using the additional user input options.

**Comment by anikfal** [comment]
What about the shadow mask? Any special algorithm is implemented in pySEBAL regarding the calculation of the shadow mask?

**Comment by TimHessels** [comment]
The same for the shadow mask. This uses normally a buffer zone around the cloud mask and by using the QC maps. But a more advanced method can be developed before running the model by using this layer as an input file.
