### ISSUE TITLE
pySEBAL error when using Landsat 7

### ISSUE THREAD

**Issue by Cris-Rogers** [TimHessels/SEBAL#14]
I was using the pySEBAL_dev_3.8
(it was noted in the pySEBAL code that you are one of the authors)

Landsat 8 and 9 are working but when I am using the Landsat 7, the generated ETa maps are blank and upon checking the text. “nan” values are indicated for important parameters starting from the tcoldmin and tcoldmax which cascades to the sensible heat and dT estimation. 
May I ask about the possible reasons about this issue? I tried to follow the manual for 3.4 by removing the other thermal band  (VCID2) and by renaming the other to end with “B6”.
 
Thank you for your kind consideration and I am hoping to hear from you.

**Comment by TimHessels** [comment]
Hi, I am not very familiar with the pySEBAL_dev_3.8 version of pySEBAL. Did you also test the latest version of pySEBAL on this Github page? And do you receive the same error?

**Comment by Cris-Rogers** [comment]
Sorry for the inconvenience, I must've misunderstood. I initially thought you were also involved with developing the 3.8 version and that this pySEBAL is related to the latter. I am yet to explore the SEBAL model in this repository. 
Thank you for your kind response.
