### ISSUE TITLE
Hot and cold pixel values for the VIIRS_PROBAV run

### ISSUE THREAD

**Issue by anikfal** [TimHessels/SEBAL#4]
Considering the VIIRS_PROBAV run, I used 0 and 0.2 for the cold and hot pixels respectively. The model ran without any error. However, the output variables relevant to the satellite data are not logical.

Some outputs such as `PROBAV_VIIRS_ts_dem_100m_2019_106`, `PROBAV_VIIRS_hot_pixels_100m_2019_106`, `PROBAV_VIIRS_cold_pixels_100m_2019_106`, and `PROBAV_QC_MAP_After_VIS_375m_2019_106` are missing or 0. And some other outputs such as `coef_A`, `coef_A`, and `coef_A` just cover very small areas, and show nodata for most parts of the area of interest, which apparently is not logical. The same condition is found for other primary outputs (evapotranspiration and radiation).

I have checked all the input data (their units and ranges), and I am pretty sure that they are correct.

**Comment by TimHessels** [comment]
Normally this is the case when pySEBAL assumes that there are clouds within the VIIRS image. Can you make sure this viirs image is cloud free?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by anikfal** [comment]
Nearly 50% of the area of interest is covered with clouds.
I multiplied the brightness temperature inside the VIIRS HDF file by the brightness temperature factors, and converted it to GeoTIFF to be used as the input data.
I can run the model for a more dry area, with less clouds, to see if makes any difference.

**Comment by anikfal** [comment]
Model results for another domain with less clouds was okay.
