### ISSUE TITLE
Alternative data for PROBA-V

### ISSUE THREAD

**Issue by anikfal** [TimHessels/SEBAL#5]
Since the PROBA-V's mission has come to an end, what alternative data are recommended to be used instead of PROBA-V?

**Comment by TimHessels** [comment]
The best alternative would be Sentinel 2, which also has a 5 daily interval and much better resolution (10m) compared to PROBA-V.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
