### ISSUE TITLE
Cloud mask and shadow mask are spatially inconsistent

### ISSUE THREAD

**Issue by anikfal** [TimHessels/SEBAL#8]
I think the spatial pattern of the shadow mask must conform to that of the cloud mask. In other words, the areas without clouds, should not contain any shadow. In my run, the spatial pattern of clouds and shadows are totally different. What could be the possible reasons?

**Comment by TimHessels** [comment]
I have updated the cloud mask component. Please let me know if you still see some issues.
If so, please share the LS tile name (path/row and date). So I can check this specific image.

**Comment by anikfal** [comment]
Could I know the details of your updates regarding the cloud mask component?

**Comment by TimHessels** [comment]
I do not know the update of one year ago any more, sorry. Please compare the versions to find the difference. If you think that a certain class of the QC map needs to be included, you can let me know, I can check and include that class.
